#!/bin/bash
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# keep this in-sync with mhwd

mkdir -p /usr/lib32

ln -sf /usr/lib32/mesa/libGL.so.1.2.0 /usr/lib32/libGL.so
ln -sf /usr/lib32/mesa/libGL.so.1.2.0 /usr/lib32/libGL.so.1
ln -sf /usr/lib32/mesa/libGL.so.1.2.0 /usr/lib32/libGL.so.1.2.0
ln -sf /usr/lib32/mesa/libGLESv1_CM.so.1.1.0 /usr/lib32/libGLESv1_CM.so
ln -sf /usr/lib32/mesa/libGLESv1_CM.so.1.1.0 /usr/lib32/libGLESv1_CM.so.1
ln -sf /usr/lib32/mesa/libGLESv1_CM.so.1.1.0 /usr/lib32/libGLESv1_CM.so.1.1.0
ln -sf /usr/lib32/mesa/libGLESv2.so.2.0.0 /usr/lib32/libGLESv2.so
ln -sf /usr/lib32/mesa/libGLESv2.so.2.0.0 /usr/lib32/libGLESv2.so.2
ln -sf /usr/lib32/mesa/libGLESv2.so.2.0.0 /usr/lib32/libGLESv2.so.2.0.0
ln -sf /usr/lib32/mesa/libEGL.so.1.0.0 /usr/lib32/libEGL.so
ln -sf /usr/lib32/mesa/libEGL.so.1.0.0 /usr/lib32/libEGL.so.1
ln -sf /usr/lib32/mesa/libEGL.so.1.0.0 /usr/lib32/libEGL.so.1.0.0
