#!/bin/sh

[[ -r /opt/livecd/util.sh ]] && source /opt/livecd/util.sh

load_profile_config "/opt/livecd/profile.conf"

[[ -r /opt/livecd/util-livecd.sh ]] && source /opt/livecd/util-livecd.sh

CONSOLEFONT="$(kernel_cmdline vconsole.font)"
CONSOLEMAP="$(kernel_cmdline vconsole.font.map)"
PACMAN_LNG="pacman --config /opt/livecd/pacman-lng.conf --noconfirm --noprogressbar"
arch=$(uname -m)

echo "update fstab for swap" > /tmp/livecd.log

## Systemd should do it
# scan_swap
configure_swap

echo "set locale" >> /tmp/livecd.log

# set language
configure_language
locale-gen

echo "configure system" >> /tmp/livecd.log

# add BROWSER var
configure_env

configure_machine_id

echo "configure sudoers" >> /tmp/livecd.log

# do_fix_perms
configure_sudo

echo "depmod extramodules" >> /tmp/livecd.log

# depmod extramodules
depmod $(cat /usr/lib/modules/$(uname -r)/extramodules/version)

install_localization

configure_displaymanager

echo "configure root password" >> /tmp/livecd.log

configure_user_root /
cp -a /etc/skel/. /root/

# configure documentation
[[ -e "/etc/skel/Manjaro/Beginner_User_Guide.pdf" ]] && ln -sf \
/etc/skel/Manjaro/Beginner_User_Guide.pdf "/home/${username}/Desktop/Beginner User Guide.pdf"

# check if we are running inside a virtual machine and unistall kalu
[[ -e "/usr/bin/kalu" ]] && rm_kalu /

configure_alsa /

# save settings
alsactl -f /etc/asound.state store &>/dev/null


